
global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanage@xxx.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  repeat_interval: 1h
  receiver: operations-team

receivers:
- name: 'operations-team'
  email_configs:
  - to: 'operations-team+alerts@example.org'
  slack_configs:
  - api_url: https://hooks.slack.com/services/xxxxxxxx/xxxxxxxxxxxxxx
    channel: '#xalert'
    send_resolved: true
